name: dev
variables:
  - name: baseUrl
    value: http://127.0.0.1:28417
  - secret: true
    name: authToken
  - secret: true
    name: invitationEmail
  - secret: true
    name: invitationToken
  - secret: true
    name: organizationMemberId
  - secret: true
    name: invitationId
  - secret: true
    name: registrationEmail
  - secret: true
    name: organizationRegistrationToken
  - secret: true
    name: memberRoleId
  - secret: true
    name: roleId
  - secret: true
    name: loginChallengeId
  - secret: true
    name: loginCode
  - secret: true
    name: sessionId
