info:
  name: create
  type: http
  seq: 2

http:
  method: POST
  url: "{{baseUrl}}/v1/iam/roles?response=resource&include=permissions"
  body:
    type: json
    data: |-
      {
        "name": "Sales Manager",
        "description": "Manages sales",
        "is_active": true,
        "permission_ids": []
      }
  auth: inherit

runtime:
  scripts:
    - type: after-response
      code: bru.setEnvVar('roleId', res.body.data.id)

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
