info:
  name: update
  type: http
  seq: 4

http:
  method: PATCH
  url: "{{baseUrl}}/v1/iam/roles/{{roleId}}?response=resource&include=permissions"
  body:
    type: json
    data: |-
      {
        "description": "Manages regional sales"
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
